- name: docker build and push
  hosts: k8s  # Replace with the hostname or IP address of your target server
  become: yes  # Run tasks with sudo privileges
  tasks:
    - name: Build Docker Image
      command: docker build -t k8s .
      args:
        chdir: /var/lib/jenkins/workspace/jenkins-ansible/Ansible/deployment.yml
    - name: tag image
      command: docker tag k8s:14
    - name: Log in to Docker Hub
      community.docker.docker_login:
        registry_url: https://index.docker.io/v1/
        username: ramanijadala
        password: dckr_pat_Exvv-2BEaMJv1lLvzvo06xelUjY
    - name: Push image
      command: docker push ramanijadala/k8s:14
    - name: Run container
      command: docker run -d --name mcapp -p 8081:8080 ramanijadala/k8s:14
